// src/App.tsx
import './App.css'
import {Background} from "./components/Background.tsx";
import Header from "./components/Header.tsx";
import {useEffect, useState} from "react";
import {Resume} from "./types.ts";
import Role from "./components/resume/Role.tsx";
import Employer from "./components/resume/Employer.tsx";

function App() {
    const [loading, setLoading] = useState<boolean>(true)
    const [resume, setResume] = useState<Resume>()

    useEffect(() => {
            fetch("https://api.github.com/repos/bncarey42/resume/contents/resume.json?ref=main", {
                method: 'GET',
                headers: new Headers({"Accept": "application/vnd.github.VERSION.raw"}),

            })
                .then(response => response.json())
                .then(data => {
                    setResume(data);
                })
                .catch(error => console.error('error', error))
                .finally(() => {
                    setLoading(false);
                });

        }
        , []);

    return (
        <Background>
            <div className={"h-screen"}>
                <div className={"mx-auto min-h-screen max-w-screen-xl px-6 py-12 md:px-12 md:py-20 lg:px-8 lg:py-0"}>
                    <div className={"lg:flex lg:justify-between lg:gap-4 "}>
                        <Header title={"Ben Carey"} subtitle={"Subtitle"} tagline={"Software Engineer"} links={[{
                            showTitle: false,
                            icon: 'devicon-github-original ',
                            title: 'GitHub',
                            href: 'https://github.com/bncarey42'
                        }]} pages={[]} skills={[]} photo={'https://avatars.githubusercontent.com/u/11987913?v=4'}/>

                        <div className={"lg:w-1/2 lg:py-24 "}>
                            <div className={"section"}>
                                <h2>Hello There</h2>
                                <p>I am a systems-minded software engineer with a client-focused mindset
                                    with {new Date().getFullYear() - 2017} years of development and engineering
                                    experience.
                                    I am questioning and curious, focusing on simplifying big problems to implement
                                    effective and maintainable solutions. I am a lifelong learner searching for ways to
                                    expand my understanding of fundamental and complex ideas.</p>
                            </div>

                            <div className={'section'}>
                                <h2>Experience</h2>
                                {
                                    resume?.work.map((employer, idx) =>
                                        <Employer
                                            employer={employer.employer}
                                            startDate={employer.startDate}
                                            endDate={employer.endDate}
                                            roles={employer.roles}/>)
                                }
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </Background>
    )
}

export default App

// src/App.vue
<script setup>
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import Resume from "./components/resume/Resume.vue";
// import htmlToPdf from "./compostables/htmlToPaper.js";
import Card from "./components/base/Card.vue";
import Hero from "./components/hero.vue";
</script>
<template>
  <div class="m-4 lg:m-24 pill-scroll font-ubuntu">
    <div class="py-8 relative">
      <div class="-z-10 absolute top-0 left-0 w-full h-full opacity-50">
        <div class="bg-hex bg-repeat-y h-full rounded-2xl lg:mx-10 mx-4 relative"></div>
      </div>
      <div class="">
        <hero title="Hello there! I'm Ben." :msg="`I am a systems-minded software engineer with a client-focused mindset with ${new Date().getFullYear() - 2017} years of development and engineering experience. I am questioning and curious, focusing on simplifying big problems to implement effective and maintainable solutions.
        I am a lifelong student searching for ways to expand my understanding of fundamental and complex ideas.`"
              :links="sites"
        />
        <card class="flex justify-center" v-if="loading">
          <h5>LOADING</h5>
        </card>

        <resume :resume="resume" v-else/>
      </div>
    </div>
  </div>
</template>
<script>
// const loading = ref(true);
export default {
  data() {
    return {
      resume: {work: []},
      sites: [
        {
          icon: "uil uil-github",
          title: "github.com/bncarey42",
          link: "https://github.com/bncarey42",
        },
        {
          icon: "uil uil-linkedin",
          title: "linkedin.com/in/benjamintcarey",
          link: "https://www.linkedin.com/in/benjamintcarey/",
        },
      ],
      loading: true
    }
  },
  created() {
    fetch("https://api.github.com/repos/bncarey42/resume/contents/resume.json?ref=main", {
      method: 'GET',
      headers: new Headers({"Accept": "application/vnd.github.VERSION.raw"}),

    })
        .then(response => response.json())
        .then(data => {
          this.resume = data;
        })
        .catch(error => console.error('error', error))
        .finally(() => {
          this.loading = false;
        });

  }
}
</script>
<style></style>
